### PR TITLE
Support real-time video demo

### PR DESCRIPTION
**Pull request by lordet01**
I added demo_video.py to demonstrate EfficientDet model on real-time video files or webcam.

Tested on Windows10, CUDA 10.2,  pytorch 1.4.0. (2020-04-18)

### CODE REVIEW

**Comment by zylo117** [comment]
1. can you remove the irrelevant files like .vscode* ?
2. can you revert the files that are unchanged? I saw you have changed their mod.
3. can you not rename utils/ to util/?

**Comment by lordet01** [comment]
1. I added .vscode to .gitignore as exception
2. I can't understand what 'mod' means. Can you let me know more details?
3. I found that from utils.utils arises error on Windows platform. For compatibility issue, i changed folder name from utils to util to avoid ambiguity between folder and file names.

**Comment by zylo117** [comment]
I am guessing you are coding on windows as admin user? The 'mod' on linux is short for mode, it means permissions. In this case, you have accidently changed the permission from 644 to 755. That's why you have so many changed files.

**Comment by zylo117** [comment]
And it's not compatibility issue, you must have somehow install a package named utils already. You can check it up using `pip list` or 'conda list` if using conda

**Comment by lordet01** [comment]
According to your request, I cleaned up my commits to minimize change in your code base. Please check whether it is now OK to merge. Thank you.

**Comment by deepseek** [comment]
@zylo117 any thoughts?

**Comment by zylo117** [comment]
thanks, but I'm sorry, I've merged another request, which is almost the same as yours.
It's tough to choose between you two, because you are doing almost the same thing. But this is conflicting. You are doing great. I'm truly sorry for not merging you.
But look at the bright side, this repo finally supports video and webcam inference, thanks to you guys. You guys are the best.

**Comment by lordet01** [comment]
OK, thank you again for sharing your great works. Closing this request.

**Pull request closed without merging**
