### PR TITLE
use latest saved weights in tutorial

### PR DESCRIPTION
**Pull request by shreyas-bk**
Use latest saved weights by default in tutorial, but also allow user to specify a weight file.

### CODE REVIEW

**Comment by zylo117** [comment]
I find out the the weight_file will always be `tensorboard`, you?

**Comment by shreyas-bk** [comment]
Using ls -Art | tail -n 1 after the training is done should return the latest saved weight file.

It worked when I ran it.

**Comment by shreyas-bk** [comment]
Example run:
tutorial_pic

**Comment by zylo117** [comment]
But `ls -Art` returns the files sorted by modification time and somtimes tensorboard will be the last to be modified.
How about using `ls -Art | tail -n 2| grep efficientdet` instead?

**Comment by shreyas-bk** [comment]
I've changed it to `ls -Art | grep efficientdet` so weight_file is a list storing all the efficientdet weight files' names, and to access the latest saved weight_file, I've changed weight_file[0] to weight_file[-1]. Would this be correct?

**Comment by zylo117** [comment]
It should be.

**Pull request merged**
